const lyrics = {
    0: {
        name: `5 Years`,
        link: `https://open.spotify.com/track/03VHtFPzSj2OnWcM7SiIWn?si=ce7a91db1e58457a`,
        lyrics: [
            `i am who i am`,
            `that does not mean i can’t`,
            `be who i want to be`,
            `i am regardless of who they see`,
            `regardless of who they see`,
            `-`,
            `i can’t pretend to know the reason`,
            `why life is fast at the worst times`,
            `and i put all my hope in a feeling`,
            `and it’s just not the same as the first time`,
            `why would i waste one more day`,
            `for something i could measure on a stopwatch?`,
            `why do i want`,
            `what i do not?`,
            `-`,
            `i’m still dancing on the camera`,
            `like i don’t know why i’m quiet around you`,
            `guess i’m not a fan of my timbre`,
            `and i can’t seem to smile right`,
            `i’ve been one the front for like 5 years`,
            `5 years that i’d never take back`,
            `i hate some things that i did`,
            `but there were things that i said that`,
            `that i never thought i’d say so`,
            `i don’t know`,
            `-`,
            `so i’ll just take a moment to remember who i am`,
            `and get back on my feet because to fear was not the plan`,
            `why am i so scared?`,
            `-`,
            `i am regardless of who they see (x3)`,
            `cuz the eyes of the lord just see me for me (x2)`,
            `-`,
            `i go to church every sunday on the dot`,
            `and I listen then I pray and I seem what I am not`,
            `they love me cuz they know they should`,
            `and that’s great`,
            `but do they come for the works?`,
            `‘cuz they’re gone, ‘cuz it’s late`,
            `-`,
            `i am regardless of who they see (x3)`,
            `‘cuz the eyes of the lord just see me for me`,
            `-`,
            `i see the flaws every sunday on the dot`,
            `but who’s in the wrong when i don’t tell them what i thought`,
            `the words they pile up`,
            `and i’ve been silent for too long`,
            `but i never said enough`,
            `like the man in my songs`,
            `-`,
            `but like the man in my songs`,
            `i’ll let it all go`,
            `what yours in not mine but what’s mine is all yours`,
            `i’ll spend all my time and not know what for`,
            `and still won’t even know what I feel at the core`,
            `-`,
            `why would i waste one more day`,
            `for something i could measure on a stopwatch`,
            `why do i want`,
            `what i do not`
        ]
    }
    
}

export default lyrics